package org.kie.package3;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(56b76c8135f802f576ce27e9a8c1e8a2)
 */
public class Pojo3  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 0)
    private org.kie.package1.Pojo1 pojo1;
    
    @org.kie.api.definition.type.Position(value = 1)
    private org.kie.package2.Pojo2 pojo2;

    public Pojo3() {
    }

    public Pojo3(org.kie.package1.Pojo1 pojo1, org.kie.package2.Pojo2 pojo2) {
        this.pojo1 = pojo1;
        this.pojo2 = pojo2;
    }


    
    public org.kie.package1.Pojo1 getPojo1() {
        return this.pojo1;
    }

    public void setPojo1(org.kie.package1.Pojo1 pojo1) {
        this.pojo1 = pojo1;
    }
    
    public org.kie.package2.Pojo2 getPojo2() {
        return this.pojo2;
    }

    public void setPojo2(org.kie.package2.Pojo2 pojo2) {
        this.pojo2 = pojo2;
    }
}