package org.kie.package1;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(ed3a8f08df9a719b077497bbf0d7b26f)
 */
public class Pojo1  implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Pojo1() {
    }




}