package org.kie.package2;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(4122bd8e6df09345b2001e4fe3f8f1c5)
 */
public class Pojo2  implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Pojo2() {
    }




}