package org.kie.sourcepreservation1;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(9c8d3fc2e58c45e76730f31724eaeae9)
 */
public class DefaultJavaTypes  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 16)
    private java.math.BigDecimal o_BigDecimal;
    
    @org.kie.api.definition.type.Position(value = 17)
    private java.math.BigInteger o_BigInteger;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Boolean o_Boolean;
    
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.Byte o_Byte;
    
    @org.kie.api.definition.type.Position(value = 5)
    private java.lang.Character o_Character;
    
    @org.kie.api.definition.type.Position(value = 18)
    private java.util.Date o_Date;
    
    @org.kie.api.definition.type.Position(value = 7)
    private java.lang.Double o_Double;
    
    @org.kie.api.definition.type.Position(value = 9)
    private java.lang.Float o_Float;
    
    @org.kie.api.definition.type.Position(value = 11)
    private java.lang.Integer o_Integer;
    
    @org.kie.api.definition.type.Position(value = 13)
    private java.lang.Long o_Long;
    
    @org.kie.api.definition.type.Position(value = 15)
    private java.lang.Short o_Short;
    
    @org.kie.api.definition.type.Position(value = 19)
    private java.lang.String o_String;
    
    @org.kie.api.definition.type.Position(value = 0)
    private boolean p_boolean;
    
    @org.kie.api.definition.type.Position(value = 2)
    private byte p_byte;
    
    @org.kie.api.definition.type.Position(value = 4)
    private char p_char;
    
    @org.kie.api.definition.type.Position(value = 6)
    private double p_double;
    
    @org.kie.api.definition.type.Position(value = 8)
    private float p_float;
    
    @org.kie.api.definition.type.Position(value = 10)
    private int p_int;
    
    @org.kie.api.definition.type.Position(value = 12)
    private long p_long;
    
    @org.kie.api.definition.type.Position(value = 14)
    private short p_short;

    public DefaultJavaTypes() {
    }

    public DefaultJavaTypes(boolean p_boolean, java.lang.Boolean o_Boolean, byte p_byte, java.lang.Byte o_Byte, char p_char, java.lang.Character o_Character, double p_double, java.lang.Double o_Double, float p_float, java.lang.Float o_Float, int p_int, java.lang.Integer o_Integer, long p_long, java.lang.Long o_Long, short p_short, java.lang.Short o_Short, java.math.BigDecimal o_BigDecimal, java.math.BigInteger o_BigInteger, java.util.Date o_Date, java.lang.String o_String) {
        this.p_boolean = p_boolean;
        this.o_Boolean = o_Boolean;
        this.p_byte = p_byte;
        this.o_Byte = o_Byte;
        this.p_char = p_char;
        this.o_Character = o_Character;
        this.p_double = p_double;
        this.o_Double = o_Double;
        this.p_float = p_float;
        this.o_Float = o_Float;
        this.p_int = p_int;
        this.o_Integer = o_Integer;
        this.p_long = p_long;
        this.o_Long = o_Long;
        this.p_short = p_short;
        this.o_Short = o_Short;
        this.o_BigDecimal = o_BigDecimal;
        this.o_BigInteger = o_BigInteger;
        this.o_Date = o_Date;
        this.o_String = o_String;
    }


    
    public java.math.BigDecimal getO_BigDecimal() {
        return this.o_BigDecimal;
    }

    public void setO_BigDecimal(java.math.BigDecimal o_BigDecimal) {
        this.o_BigDecimal = o_BigDecimal;
    }
    
    public java.math.BigInteger getO_BigInteger() {
        return this.o_BigInteger;
    }

    public void setO_BigInteger(java.math.BigInteger o_BigInteger) {
        this.o_BigInteger = o_BigInteger;
    }
    
    public java.lang.Boolean getO_Boolean() {
        return this.o_Boolean;
    }

    public void setO_Boolean(java.lang.Boolean o_Boolean) {
        this.o_Boolean = o_Boolean;
    }
    
    public java.lang.Byte getO_Byte() {
        return this.o_Byte;
    }

    public void setO_Byte(java.lang.Byte o_Byte) {
        this.o_Byte = o_Byte;
    }
    
    public java.lang.Character getO_Character() {
        return this.o_Character;
    }

    public void setO_Character(java.lang.Character o_Character) {
        this.o_Character = o_Character;
    }
    
    public java.util.Date getO_Date() {
        return this.o_Date;
    }

    public void setO_Date(java.util.Date o_Date) {
        this.o_Date = o_Date;
    }
    
    public java.lang.Double getO_Double() {
        return this.o_Double;
    }

    public void setO_Double(java.lang.Double o_Double) {
        this.o_Double = o_Double;
    }
    
    public java.lang.Float getO_Float() {
        return this.o_Float;
    }

    public void setO_Float(java.lang.Float o_Float) {
        this.o_Float = o_Float;
    }
    
    public java.lang.Integer getO_Integer() {
        return this.o_Integer;
    }

    public void setO_Integer(java.lang.Integer o_Integer) {
        this.o_Integer = o_Integer;
    }
    
    public java.lang.Long getO_Long() {
        return this.o_Long;
    }

    public void setO_Long(java.lang.Long o_Long) {
        this.o_Long = o_Long;
    }
    
    public java.lang.Short getO_Short() {
        return this.o_Short;
    }

    public void setO_Short(java.lang.Short o_Short) {
        this.o_Short = o_Short;
    }
    
    public java.lang.String getO_String() {
        return this.o_String;
    }

    public void setO_String(java.lang.String o_String) {
        this.o_String = o_String;
    }
    
    public boolean isP_boolean() {
        return this.p_boolean;
    }

    public void setP_boolean(boolean p_boolean) {
        this.p_boolean = p_boolean;
    }
    
    public byte getP_byte() {
        return this.p_byte;
    }

    public void setP_byte(byte p_byte) {
        this.p_byte = p_byte;
    }
    
    public char getP_char() {
        return this.p_char;
    }

    public void setP_char(char p_char) {
        this.p_char = p_char;
    }
    
    public double getP_double() {
        return this.p_double;
    }

    public void setP_double(double p_double) {
        this.p_double = p_double;
    }
    
    public float getP_float() {
        return this.p_float;
    }

    public void setP_float(float p_float) {
        this.p_float = p_float;
    }
    
    public int getP_int() {
        return this.p_int;
    }

    public void setP_int(int p_int) {
        this.p_int = p_int;
    }
    
    public long getP_long() {
        return this.p_long;
    }

    public void setP_long(long p_long) {
        this.p_long = p_long;
    }
    
    public short getP_short() {
        return this.p_short;
    }

    public void setP_short(short p_short) {
        this.p_short = p_short;
    }
}