package org.kie.sourcepreservation1;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(4cd74d41b9cf0ae69e0712d1f0ace21d)
 */
public class Pojo1  implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Pojo1() {
    }




}